### PR TITLE
Add section 2 references to bib file

### PR DESCRIPTION
**Pull request by brymz**

### CODE REVIEW

**Comment by ethanwhite** [comment]
This looks great, but it looks like the merge is conflicted, probably due to my changes last night to section 4 that included adding references to it.

**Comment by brymz** [comment]
I sent you my file today if you just want to add the lines to your copy.

**Comment by ethanwhite** [comment]
Sounds good. I've been messing around with getting this to merge in smoothly for about an hour, but it would require more work on your end, so I'll just add it on mine.

**Comment by brymz** [comment]
Sorry for the extra effort.

**Comment by ethanwhite** [comment]
No problem. Part of the growing pains of expanding the sophistication of our Git approaches. Happy to pay the price.

This is now merged as of f501b517cce039f4ad8ee81bc08fd1b900bf2b0d.

**Pull request closed without merging**
