### PR TITLE
Format nullvalues

### PR DESCRIPTION
**Pull request by embaldridge**
This is the draft of the null values section and the introduction to the standard format section.  Most of the standard format section will be in a figure in a separate file, and I am still working on getting that to look presentable.

### CODE REVIEW

**Comment by dmcglinn** [comment]
Looks great, I'm going to go ahead and merge

**Comment by dmcglinn** [comment]
I may have commented too quickly the merge pull request button has disappeared on me. Can someone else please merge these changes.

**Comment by ethanwhite** [comment]
I've merged this in. Those of you working on your own forks will now want to run:

```
git fetch upstream
git merge upstream/master
```

to get the changes into your working forks.

**Comment by embaldridge** [comment]
Don't forget to run

git remote add upstream <main repo>

first, else you will get an error.

**Pull request merged**
