### PR TITLE
Final cleanup

### PR DESCRIPTION
**Pull request by ethanwhite**
I'm a bit glazed after fighting with tables all morning so can someone give this a quick look to make sure I didn't mess anything up.

### CODE REVIEW

**Comment by embaldridge** [comment]
Looks good to me, anyone else spot anything?

**Comment by dmcglinn** [comment]
The formatting of the last sentence in the share your data section needs to be fixed so that it is in line with the previous paragraph.

**Comment by klocey** [comment]
Nice catch, Dan. Looks good to me.

**Comment by ethanwhite** [comment]
Fixed.

**Pull request merged**
