### PR TITLE
Sections 9 and 10

### PR DESCRIPTION
**Pull request by klocey**
I've added a section on repositories (9) and one on licensing (10). Section 9 (repos) includes an uncompleted table that might not currently agree with the table caption and may not be wholly correct. Feel free to make suggestions about which repos and what data about repos to include. I like the conditions in the table caption. -KJL

### CODE REVIEW

**Comment by dmcglinn** [comment]
This changes look good to me. For some reason the automatic merge button says "This pull request cannot be automatically merged".  Does anyone know why this would be?

**Comment by klocey** [comment]
Not me. However, I'm meeting with Ethan in a bit. I'm sure we'll get it straightened out.

**Comment by embaldridge** [comment]
Ken, did you do

git fetch upstream/master

and

git merge upstream/master?

On Thu, Mar 7, 2013 at 2:00 PM, Kenneth John Locey <notifications@github.com

**Comment by klocey** [comment]
Yup, I imagine it has something to do with commands.

**Comment by ethanwhite** [comment]
There's a conflict with the merge so it can't be done automatically. I would have suggested what Elita did, so I'll just stick my head over and see if we can figure it out.

**Comment by klocey** [comment]
Thanks guys. There was a conflict with a special character.

**Comment by ethanwhite** [comment]
And actually there's still some weird stuff going on so please don't merge this yet...

**Comment by ethanwhite** [comment]
OK, this is all sorted out now. Basically the histories were out of sync enough that when a special character crept in and caused a conflict the history got really messy. I fixed this using the following:

```
git reset --hard HEAD^
```

to get rid of the commit from my first attempt at cleaning this up (this resets to the next to last commit, indicated by the ^)

```
git rebase upstream/master
```

rebase is an alternative to merge that replays commits in order to give cleaner histories. This leads to a conflict based on the special character that I resolved manually by editing the conflicted file and then

```
git add data_sharing_ms.md
git rebase --continue
```

**Comment by dmcglinn** [comment]
you are a git wizard! thank you for giving us the run down of the 
problem and your solution.

Dan
-------- Original Message --------
Subject: Re: [data-sharing-paper] Sections 9 and 10 (#8)

**Comment by klocey** [comment]
Git + wizard = Gizzard. Ethan is a specialized stomach constructed of thick, muscular walls used for grinding data and silicon related problems; ingested rocks are often instrumental.

**Comment by ethanwhite** [comment]
Hilarious! :laughing:

**Pull request merged**
