### PR TITLE
Adding mention of Panton Principles to License section. Fixes #99.

### LINKED ISSUE #99: Mention Paton Principles in Licensing section
Carl Boettiger (#71):

> You might mention established recommendations such as http://pantonprinciples.org/

### PR DESCRIPTION
**Pull request by ethanwhite**
I did a little restructuring to get this in without bogging things down. Let me know if it doesn't work.

### CODE REVIEW

**Comment by embaldridge** [comment]
I think it works.  Anyone else?

**Comment by sarahsupp** [comment]
I'm on board.

**Comment by ethanwhite** [comment]
Great, thanks.

**Comment by ethanwhite** [comment]
Given the minor change, general support, and lack of objection, I'm going to go ahead and merge this.

**Pull request merged**
