### PR TITLE
Issue #74 fix

### PR DESCRIPTION
**Pull request by embaldridge**
Provides a stronger recommendation for .csv, and secondarily, tab-delimited files.  Feels a little clunky to me, so if anyone has any ideas on how to improve the flow, jump in.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Weren't the delimiter issues already addressed in https://github.com/weecology/data-sharing-paper/pull/111? Do you think we need more?

**Comment by embaldridge** [comment]
This was the clarification of the .xls, .xlsx thing, with a stronger
recommendation for "use these file types", and a brief mention of other
proprietary formats as "and others".

**Comment by ethanwhite** [comment]
OK, sounds good. I like it.

The issue with tabs isn't how they are defined (I'm pretty sure that's always the same), it's with how they are displayed. So, things that appear nicely lined up in one case look like a jumbled mess in another. I'm also not sure this is an OS thing. I think it's probably just a program thing.

I see what you're trying to do with "and others", but it reads a bit funny. We should either cut it and just count on the "such as" getting the point across or make it "and other spreadsheets" or "and other programs". I'd lean towards cutting it, but I don't feel strongly about it.

**Comment by embaldridge** [comment]
Okay, I think that looks better now.  Thank you for clarifying the tab
problem.  I cut the "and others" bit; I think people can figure out that if
it is not .csv or tab-delimited, it is probably proprietary.

**Pull request merged**
