### PR TITLE
Trying to make the introduction flow better

### PR DESCRIPTION
**Pull request by ethanwhite**
I just spent way too long struggling to make the Introduction flow better. The challenge is that the last paragraph is, at its core, a paragraph about why most of our recommendations are beneficial for the individual collecting the data as well. This isn't really a good jumping off point for the rest of the ms. Since we all like the idea of having this material in the Intro (preventing us from just dropping most of the last paragraph) I've tried to make it flow better while holding on to the current material. I'm not at all sure that I have succeeded, so let's have a discussion about what I've tried before any merging occurs.

### CODE REVIEW

**Comment by embaldridge** [comment]
What if we restructured that paragraph so that it funnels from sharing from
the wider community, to in-house collaboration, to personal use?  That way,
we end on the personal benefits of good data structure and sharing and the
paragraph goes from more general to more specific.

In ecology and evolutionary biology, sharing occurs through a
combination of formal data repositories like GenBank ([
http://www.ncbi.nlm.nih.gov/genbank/](http://www.ncbi.nlm.nih.gov/genbank/)
) and Dryad ([http://datadryad.org/](http://datadryad.org/)
), and through individual and institutional websites.
While data sharing is increasingly common and straightforward, much of
the shared data is not easily reused because it does not follow best
practices in terms of data structure, metadata, and licensing
[@jones2006].

This makes it more difficult to work with existing data and therefore
makes the data less useful than it could be [@jones2006;
@reichman2011].
The most usable data is understandable, easy to work with, and
available to the wider community of scientists.
Data sharing often occurs within a research group.
Good data sharing practices make these in-house collaborations faster,
easier, and less dependent on lab members who may have graduated or
moved on to other things.
Well organized data with good documentation makes it easier for anyone
to work with the data, including you.
This is particularly true when returning to your own data for further
analysis months or years after you originally collected or analyzed
it.
Here we provide a list of nine simple ways to make it easier for
others to reuse the data that you share and for you to use it
yourself.

Elita

**Comment by klocey** [comment]
> (Ethan) ...the last paragraph is, at its core, a paragraph about why most
> of our recommendations are beneficial for the individual collecting the
> data as well. This isn't really a good jumping off point for the rest of
> the ms

Maybe I'm wrong, but Ethan is suggesting to not end on 'personal benefits',
as most of the paper pertains to making data easier for others to use (e.g.
First section title is Share your data). So the current last paragraph
isn't a good jumping off-point, as is.

Here's a start...

Here we provide a list of 9 simple ways that make it easier to share and
reuse your data. Well organized data in a consistent format with useful
documentation makes it easier for anyone to work with a dataset. This is
particularly true when returning to analyze, curate, or add to your data
months or years after original collection. In addition, data sharing often
occurs within a lab or research group, and many hours can be lost to
reorganizing inconsistently formatted data and to deciphering ambiguous
columns, rows, and metadata. Likewise, these problems and the potential for
systemic error are only exacerbated outside the open communication of a lab
or research group, where the research of colleagues may hinge on your
willingness to make your data as easily accessible and usable as possible.
Consequently, our recommendations largely focus on making your data
understandable, easy to work with, and available to the wider community of
scientists.

Ken

**Comment by sarahsupp** [comment]
I think that Ethan's comment was that ending on the individual-level benefits isn't a great way to jump off for a paper that is primarily focused on sharing data for group-level benefits. Although I agree that pointing out, even briefly, that this benefits the individual, is a good thing to do here.

I feel that one problem is that the current introduction lacks a good topic sentence. The first sentence focuses on where data is shared, but that's not really the point here. Why was the previous topic sentence deleted?

Maybe if we push the individual benefits further up, to logically follow from why developing good habits is good for you. Then we can suggest that although sharing is good and becoming more common, that we just aren't doing it right. This paper will help you learn that...

---Sarah---
Sharing data is increasingly recognized as an important component of the scientific process [@whitlock2010]. The sharing of scientific data is beneficial because it allows replication of research results and reuse in meta-analyses and projects not originally intended by the data collectors [@poisot2013]. The most usable data is understandable, easy to work with, and available to the wider community of scientists. In addition to the scientific community, developing good data sharing practices benefits individual researchers by ensuring that data is well described, organized, and preserved. This is particularly true when returning to your own data for further analysis months or years after you originally collected or analyzed it. Data sharing often occurs within a lab or research group. Good data sharing practices make these in-house collaborations faster, easier, and less dependent on lab members who may have graduated or moved on to other things.

While data sharing is increasingly common and straightforward, much of the shared data is not easily reused because it does not follow best practices in terms of data structure, metadata, and licensing [@jones2006]. This makes it more difficult to work with existing data and therefore makes the data less useful than it could be [@jones2006; @reichman2011]. Here we provide a list of nine simple ways to make it easier for others to reuse the data that you share and for you to use it yourself.

**Comment by dmcglinn** [comment]
I like Sarah's restructuring best.

**Comment by ethanwhite** [comment]
> Maybe I'm wrong, but Ethan is suggesting to not end on 'personal benefits',
> as most of the paper pertains to making data easier for others to use
> (e.g. First section title is Share your data). So the current last paragraph isn't
> a good jumping off-point, as is.

Yes, this is exactly my concern, and in fact once you stated it so nicely I'm personally starting to wonder how much of this information should be in the Introduction. Yes, it's certainly nice to provide a good justification for why you should do some of this even if you aren't really in to data sharing, and I like having a sentence or two indicating that this is the case. However, the paper is about data sharing and as it stands we dedicate about half our intro to basically talking about why this is good even if you don't share your data publicly. This is what makes this so hard to write, so I'm leaning towards moving the good chunks of this down into the conclusions and keeping one or two sentences with the general idea in the intro.

If folks disagree with this, then I agree with Dan that Sarah's restructuring is about as good as it's going to get.

**Comment by klocey** [comment]
I agree with Ethan. That is, I like not getting bogged-down in the intro
with "why this is good even if you don't share your data publicly." Good
stuff but maybe best somewhere else.

Ken

**Comment by embaldridge** [comment]
I also like Sarah's restructuring.

Elita

On Fri, Apr 5, 2013 at 3:13 PM, Kenneth John Locey <notifications@github.com

> wrote:
> 
> I agree with Ethan. That is, I like not getting bogged-down in the intro
> with "why this is good even if you don't share your data publicly." Good
> stuff but maybe best somewhere else.
> 
> Ken
>

**Comment by klocey** [comment]
Solution: Weecology death match. Everybody grab a sock and a bar of soap.

**Comment by dmcglinn** [comment]
Ethan, assuming you survived the death match Ken proposed, your final suggestion of moving the 'why you should share' down the conclusion is fine with me.

**Comment by klocey** [comment]
Ethan cheated and pulled out a hockey stick, so he's fine. You ever fought
a high-stickin' hockey player with nothing but a sock and a bar of Irish
Spring?

**Comment by sarahsupp** [comment]
I think it would fit well in the conclusions. We already make some similar statements there anyway, so it would be pretty easy to merge the individual benefits language from the intro into the conclusion. We could still mention that there are individual-level benefits in the intro, just as an aside, but not include any details (1 sentence, or something as simple as "data sharing benefits the scientific community, and yourself"). The individual-level benefits do pop up throughout the paper, so a v. short statement in the introduction to this point seems appropriate and useful.

Were you thinking of expanding the intro in another direction, or just leaving it really concise?

**Comment by ethanwhite** [comment]
I was thinking about just keeping it really concise.

**Comment by ethanwhite** [comment]
I just put in a new pull request that attempts to implement the potential move of a lot of the personal benefits specifics from the Intro to the Conclusions in #62. Let me know what you think.

**Comment by ethanwhite** [comment]
Closing since we ended up going with #62.

**Pull request closed without merging**
